FROM python:3.11-slim
WORKDIR /app
RUN pip config set global.index-url https://pypi.org/simple
COPY python/indicator-service/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY python/indicator-service/ .
ENV LOG_DIR=/app/logs \
    LOG_ENV=prod \
    LOG_LEVEL=INFO
RUN mkdir -p /app/logs
EXPOSE 10254
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "10254"]
